<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NiveisEnsinoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $niveisEnsino = [
            // ===== EDUCAÇÃO INFANTIL =====
            [
                'nome' => 'Berçário I',
                'codigo' => 'BER1',
                'descricao' => 'Atendimento para bebês de 0 a 1 ano',
                'capacidade_padrao' => 8,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EI']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Berçário II',
                'codigo' => 'BER2',
                'descricao' => 'Atendimento para bebês de 1 a 2 anos',
                'capacidade_padrao' => 10,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EI']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Maternal I',
                'codigo' => 'MAT1',
                'descricao' => 'Educação Infantil para crianças de 2 a 3 anos',
                'capacidade_padrao' => 12,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EI']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Maternal II',
                'codigo' => 'MAT2',
                'descricao' => 'Educação Infantil para crianças de 3 a 4 anos',
                'capacidade_padrao' => 15,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EI']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Pré-Escola',
                'codigo' => 'PRE',
                'descricao' => 'Educação Infantil para crianças de 4 a 5 anos',
                'capacidade_padrao' => 20,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EI']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ENSINO FUNDAMENTAL - ANOS INICIAIS =====
            [
                'nome' => '1º Ano Fundamental',
                'codigo' => '1EF',
                'descricao' => 'Primeiro ano do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '2º Ano Fundamental',
                'codigo' => '2EF',
                'descricao' => 'Segundo ano do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '3º Ano Fundamental',
                'codigo' => '3EF',
                'descricao' => 'Terceiro ano do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '4º Ano Fundamental',
                'codigo' => '4EF',
                'descricao' => 'Quarto ano do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '5º Ano Fundamental',
                'codigo' => '5EF',
                'descricao' => 'Quinto ano do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ENSINO FUNDAMENTAL - ANOS FINAIS =====
            [
                'nome' => '6º Ano Fundamental',
                'codigo' => '6EF',
                'descricao' => 'Sexto ano do Ensino Fundamental',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '7º Ano Fundamental',
                'codigo' => '7EF',
                'descricao' => 'Sétimo ano do Ensino Fundamental',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '8º Ano Fundamental',
                'codigo' => '8EF',
                'descricao' => 'Oitavo ano do Ensino Fundamental',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '9º Ano Fundamental',
                'codigo' => '9EF',
                'descricao' => 'Nono ano do Ensino Fundamental',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EF']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ENSINO MÉDIO =====
            [
                'nome' => '1º Ano Médio',
                'codigo' => '1EM',
                'descricao' => 'Primeiro ano do Ensino Médio',
                'capacidade_padrao' => 35,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EM']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '2º Ano Médio',
                'codigo' => '2EM',
                'descricao' => 'Segundo ano do Ensino Médio',
                'capacidade_padrao' => 35,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EM']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => '3º Ano Médio',
                'codigo' => '3EM',
                'descricao' => 'Terceiro ano do Ensino Médio',
                'capacidade_padrao' => 35,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EM']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== EDUCAÇÃO DE JOVENS E ADULTOS (EJA) =====
            [
                'nome' => 'EJA Fundamental I',
                'codigo' => 'EJA1',
                'descricao' => 'EJA correspondente aos anos iniciais do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => false,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EJA']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'EJA Fundamental II',
                'codigo' => 'EJA2',
                'descricao' => 'EJA correspondente aos anos finais do Ensino Fundamental',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => false,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EJA']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'EJA Ensino Médio',
                'codigo' => 'EJA3',
                'descricao' => 'EJA correspondente ao Ensino Médio',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => false,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EJA']),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== EDUCAÇÃO PROFISSIONAL =====
            [
                'nome' => 'Técnico Integrado',
                'codigo' => 'TI',
                'descricao' => 'Ensino Médio integrado com Educação Profissional',
                'capacidade_padrao' => 30,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => false,
                'turno_integral' => true,
                'modalidades_compativeis' => json_encode(['EP']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Técnico Subsequente',
                'codigo' => 'TS',
                'descricao' => 'Educação Profissional para quem já concluiu o Ensino Médio',
                'capacidade_padrao' => 25,
                'ativo' => true,
                'turno_matutino' => true,
                'turno_vespertino' => true,
                'turno_noturno' => true,
                'turno_integral' => false,
                'modalidades_compativeis' => json_encode(['EP']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Inserir ou atualizar os níveis de ensino
        foreach ($niveisEnsino as $nivel) {
            DB::table('niveis_ensino')->updateOrInsert(
                ['codigo' => $nivel['codigo']],
                $nivel
            );
        }
    }
}